# Generated by Django 3.1.7 on 2021-05-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('cause', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=50)),
                ('symptom1', models.CharField(max_length=100)),
                ('symptom2', models.CharField(max_length=100)),
                ('symptom3', models.CharField(max_length=100)),
                ('symptom4', models.CharField(max_length=100)),
                ('symptom5', models.CharField(max_length=100)),
                ('symptom6', models.CharField(max_length=100)),
                ('symptom7', models.CharField(max_length=100)),
                ('symptom8', models.CharField(max_length=100)),
                ('symptom9', models.CharField(max_length=100)),
                ('symptom10', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
    ]
