# Generated by Django 3.1.7 on 2021-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptom10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptom9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
