# Generated by Django 3.1.7 on 2021-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20210504_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('doctor', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('hospital', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
