# Generated by Django 3.1.7 on 2021-05-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_auto_20210509_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sikk',
            name='symptom21',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom22',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom23',
        ),
    ]
