# Generated by Django 3.1.7 on 2021-05-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_auto_20210509_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sikk',
            name='symptom10',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom11',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom12',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom13',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom14',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom15',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom16',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom17',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom18',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom19',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom20',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom6',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom7',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom8',
        ),
        migrations.RemoveField(
            model_name='sikk',
            name='symptom9',
        ),
    ]
