# Generated by Django 3.1.7 on 2021-05-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_auto_20210509_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sikk',
            name='symptom5',
        ),
    ]
