# Generated by Django 3.1.7 on 2021-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_remove_sikk_symptom5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cold',
            fields=[
                ('disease', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('cause', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=50)),
                ('symptom1', models.CharField(max_length=300)),
                ('symptom2', models.CharField(max_length=300)),
                ('symptom3', models.CharField(max_length=300)),
                ('symptom4', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
